# -*- coding: utf-8 -*-
"""
Created on Wed Dec 22 02:15:49 2021

@author: LENOVO
"""

#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Dec 17, 2021 08:58:02 AM CAT  platform: Windows NT


from tkinter import *

from tkinter import filedialog

from PIL import ImageTk
import PIL.Image

import sys
import PIL
from keras import models
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
import os
import glob as gb
import cv2
import tensorflow as tf
import keras
from skimage import color
from skimage import io

from tkinter import *
from PIL import Image, ImageTk
import pyttsx3
import time


def getcode(n):
    code = {'Tshirt':0 ,'Trouser':1,'Pullover':2,'Dress':3,'Coat':4,'Sandal':5,'Shirt':6,'Sneaker':7,'Bag':8,'Ankle boot':9}
    for x, y in code.items():
        if n == y:
            return x


def get_result(model,path):
    c = models.load_model(model)
    x = "xxx"
    X_image = []
    image = cv2.imread(path)
    imgGray = color.rgb2gray(image)
    image_array = cv2.resize(imgGray, (28, 28))
    X_image.append(list(image_array))
    X_test = []
    X_test.append(list(image_array))
    X_test = np.array(X_test)
    y_pred = c.predict(X_test)
    return str(getcode(np.argmax(y_pred)))


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True





def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    root.mainloop()


w = None


def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None




class Toplevel1:
    
    
    def __init__(self, top=None):
        engine=pyttsx3.init()
        def speaknow(text):
            # engine.connect('started-utterance', openFile)
            engine.setProperty('rate', 128)
            engine.say(text)
            time.sleep(1)
            engine.runAndWait()
            engine.stop()
            
            
        def openFile():
            filepath = filedialog.askopenfilename(initialdir="E:\3st\Semster_1\Projects\Selected\DataSet\Dataset\seg_pred - Copy\seg_pred")
            file = open(filepath, 'r')
            print(filepath)
            self.Label8.configure(text=get_result("D:\\university\\third year\\AI\\ObjectDetection\\model.h5",filepath))
            self.varun_label.config(image = "")
            image = Image.open(filepath)
            resized_image= image.resize((300,300), Image.ANTIALIAS)
            photo = ImageTk.PhotoImage(resized_image)
            self.varun_label.configure(image=photo)
            self.varun_label.image=photo
            speaknow(self.Label8['text'])
            
        
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x706+463+34")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1, 1)
        top.title("Object Detection program")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        




        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0, rely=0, relheight=1, relwidth=1)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#f2f2f2")
        
        
        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.085, rely=0, height=127, width=454)
        self.Label1.configure(background="#f2f2f2")
        self.Label1.configure(font=('Arial', 25))
        self.Label1.configure(foreground="#39388e")
        self.Label1.configure(text='''Welcome To Our Object''')

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.205, rely=.12, height=79, width=303)
        self.Label6.configure(background="#f2f2f2")
        self.Label6.configure(font=('Arial', 20))
        self.Label6.configure(foreground="#39388e")
        self.Label6.configure(text='''Detection Project''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.255, rely=0.250, height=60, width=250)
        self.Button1.configure(background="#01e26f")
        self.Button1.configure(font=('Arial', 25))
        self.Button1.configure(foreground="#f0fff8")
        self.Button1["border"] = "2"
        self.Button1.configure(text='''Choose Image''', command=openFile)
        

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.060, rely=0.355, height=60, width=200)
        self.Label7.configure(background="#f2f2f2")
        self.Label7.configure(font=('Arial', 20))
        self.Label7.configure(foreground="#39388e")
        self.Label7.configure(text='''Object Name is :''')

        self.Label8 = tk.Label(self.Frame1)
        self.Label8.place(relx=0.068, rely=0.450, height=40, width=180)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(font=("Courier", 18))
        
        # ########################
        self.varun_label = tk.Label(self.Frame1)
        self.varun_label.place(relx=0.068, rely=0.500)
        ########################
        
        self.Frame1.mainloop()
if __name__ == '__main__':
    vp_start_gui()


